services:
  - type: web
    name: twentyqgames
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AKEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
